const $=s=>document.querySelector(s);
const presets={comfort:{temperature:25,humidity:60,soil:65,light:80,note:'叶片舒展，土壤湿润，光照充足，植物生长正常。'},dry:{temperature:28,humidity:35,soil:10,light:75,note:'连续多日没有浇水，土壤干裂，叶片萎蔫，需要给植物补水。'},hot:{temperature:42,humidity:90,soil:70,light:85,note:'温室闷热，植物因高温萎蔫，需要打开通风设备降温。'},dark:{temperature:23,humidity:60,soil:65,light:5,note:'日照不足，温室里很暗，植物需要补充光照。'}};
const fields=[['temperature','温度','℃',50],['humidity','空气湿度','%',100],['soil','土壤湿度','%',100],['light','光照强度','%',100]];
let last=null,busy=false,ready=false,history=[],timer;
for(const [key,label,unit,max] of fields){const div=document.createElement('div');div.className='control';div.innerHTML=`<label for="${key}">${label}<output id="${key}-value"></output></label><input id="${key}" type="range" min="0" max="${max}" step="1">`;$('#sliders').append(div);$('#'+key).addEventListener('input',()=>{refresh();document.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('selected'));stale()});}
function refresh(){for(const [key,,unit] of fields)$('#'+key+'-value').innerHTML=$('#'+key).value+`<small>${unit}</small>`;}
function stale(){if(last){$('#scene-state').textContent='输入已更改 · 等待重新判断';$('#certainty').textContent='右侧为上一轮结果，请重新提交当前输入。';$('#scene').dataset.action='idle';$('#animate').disabled=true;document.querySelectorAll('.actuators span').forEach(x=>x.classList.remove('active'));}}
function select(name){const p=presets[name];for(const [key] of fields)$('#'+key).value=p[key];$('#note').value=p.note;refresh();stale();document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('selected',b.dataset.preset===name));}
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>select(b.dataset.preset));$('#note').addEventListener('input',stale);select('comfort');
function input(){const data={note:$('#note').value};for(const [key] of fields)data[key]=Number($('#'+key).value);return data;}
function pct(x){return (x*100).toFixed(1)+'%'}
function animate(){if(!last)return;const action=last.answers.action.choice;$('#scene').dataset.action=action;$('#scene-title').textContent=action==='保持'?'保持当前环境':'正在演示：'+action;$('#scene-description').textContent='动画呈现本次模型建议，未操作真实设备。';document.querySelectorAll('.actuators span').forEach(x=>x.classList.remove('active'));const tag={通风:'#fan-tag',补水:'#water-tag',补光:'#light-tag'}[action];if(tag)$(tag).classList.add('active');}
function render(result){last=result;const a=result.answers.action;const top=a.probabilities[a.choice];$('#choice').textContent=a.choice;const percent=document.createElement('span');percent.textContent=pct(top);$('#choice').append(percent);$('#certainty').textContent=top>=.55?'当前最高概率的动作建议。':'概率较分散，请人工确认后再演示。';$('#probabilities').replaceChildren();for(const [label,value] of Object.entries(a.probabilities)){const row=document.createElement('div');row.className='prob-row'+(label===a.choice?' top':'');const line=document.createElement('div'),name=document.createElement('span'),number=document.createElement('b');name.textContent=label;number.textContent=pct(value);line.append(name,number);const track=document.createElement('div'),bar=document.createElement('i');track.className='track';bar.style.width=pct(value);track.append(bar);row.append(line,track);$('#probabilities').append(row);}$('#urgency').textContent=result.answers.urgency.score.toFixed(2)+' / 2';$('#urgency-bar').style.width=pct(result.answers.urgency.score/2);$('#water').textContent=pct(result.answers.water.noul);$('#heat').textContent=pct(result.answers.heat.noul);$('#latency').textContent=result.total_python_latency_ms.toFixed(1)+' ms';$('#wall').textContent=result.wallMilliseconds.toFixed(1)+' ms';$('#scene-state').textContent='本次判断已完成';$('#animate').disabled=false;$('#export').disabled=false;if(top>=.55)animate();else{$('#scene').dataset.action='idle';$('#scene-title').textContent='建议：'+a.choice+' · 待确认';$('#scene-description').textContent='确认后点击“演示建议”，查看模拟动作。';}history.unshift({time:new Date().toLocaleTimeString('zh-CN'),state:result.request.state,choice:a.choice,probability:pct(top),latency:result.total_python_latency_ms.toFixed(1)+' ms'});history=history.slice(0,8);$('#history').replaceChildren();for(const item of history){const row=document.createElement('div');row.className='history-row';for(const [key,value] of Object.entries(item)){const el=document.createElement(key==='choice'?'strong':'span');el.textContent=value;el.title=value;row.append(el);}$('#history').append(row);}}
$('#decide').onclick=async()=>{if(busy)return;busy=true;document.querySelectorAll('input,textarea,[data-preset]').forEach(x=>x.disabled=true);$('#decide').disabled=true;$('#decide').textContent='正在算力卡上推理…';$('#error').textContent='';$('#scene-state').textContent='模型正在判断';$('#scene').dataset.action='idle';$('#animate').disabled=true;document.querySelectorAll('.actuators span').forEach(x=>x.classList.remove('active'));try{const response=await fetch('/api/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input()),signal:AbortSignal.timeout(35000)});const result=await response.json();if(!response.ok)throw Error(result.error);render(result);}catch(e){$('#error').textContent=e.message;$('#scene-state').textContent='本次判断未完成';}finally{busy=false;document.querySelectorAll('input,textarea,[data-preset]').forEach(x=>x.disabled=false);$('#decide').textContent='让 Laya 判断 ↗';$('#decide').disabled=!ready;}};
$('#animate').onclick=animate;$('#export').onclick=()=>{if(!last)return;const blob=new Blob([JSON.stringify(last,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='laya-greenhouse-result.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function status(){try{const r=await fetch('/api/status');if(!r.ok)throw Error();const s=await r.json();ready=s.status==='ready';$('#status').textContent=ready?'● 算力卡已就绪':s.status==='loading'?'◌ 正在加载模型…':'○ 模型不可用';}catch{ready=false;$('#status').textContent='○ 服务未连接';}$('#decide').disabled=!ready||busy;timer=setTimeout(status,ready?10000:2000);}status();
